# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/ecommerce/v1/cart.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'services/ecommerce/v1/cart.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import messages_pb2 as common_dot_messages__pb2
from services.ecommerce.v1 import products_pb2 as services_dot_ecommerce_dot_v1_dot_products__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n services/ecommerce/v1/cart.proto\x12\x1aservices.ecommerce.v1.cart\x1a\x15\x63ommon/messages.proto\x1a$services/ecommerce/v1/products.proto\"8\n\x10\x41\x64\x64ToCartRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"0\n\x11\x41\x64\x64ToCartResponse\x12\x1b\n\x13total_cart_products\x18\x01 \x01(\x05\"=\n\x15RemoveFromCartRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"5\n\x16RemoveFromCartResponse\x12\x1b\n\x13total_cart_products\x18\x01 \x01(\x05\"\x12\n\x10\x43learCartRequest\"\x13\n\x11\x43learCartResponse\"\x11\n\x0fViewCartRequest\"W\n\x08\x43\x61rtItem\x12\x39\n\x08products\x18\x01 \x01(\x0b\x32\'.services.ecommerce.v1.products.Product\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"g\n\x10ViewCartResponse\x12\x36\n\x08products\x18\x01 \x03(\x0b\x32$.services.ecommerce.v1.cart.CartItem\x12\x1b\n\x13total_cart_products\x18\x02 \x01(\x05\"\x92\x01\n\x0c\x43\x61rtInternal\x12#\n\x04meta\x18\x01 \x01(\x0b\x32\x15.common.messages.Meta\x12\x10\n\x08\x62uyer_id\x18\x02 \x01(\t\x12\x36\n\x08products\x18\x03 \x03(\x0b\x32$.services.ecommerce.v1.cart.CartItem\x12\x13\n\x0btotal_price\x18\x04 \x01(\x05\x32\xc1\x03\n\x0b\x43\x61rtService\x12h\n\tAddToCart\x12,.services.ecommerce.v1.cart.AddToCartRequest\x1a-.services.ecommerce.v1.cart.AddToCartResponse\x12w\n\x0eRemoveFromCart\x12\x31.services.ecommerce.v1.cart.RemoveFromCartRequest\x1a\x32.services.ecommerce.v1.cart.RemoveFromCartResponse\x12h\n\tClearCart\x12,.services.ecommerce.v1.cart.ClearCartRequest\x1a-.services.ecommerce.v1.cart.ClearCartResponse\x12\x65\n\x08ViewCart\x12+.services.ecommerce.v1.cart.ViewCartRequest\x1a,.services.ecommerce.v1.cart.ViewCartResponseB7Z5github.com/darkclown97/api/services/ecommerce/v1/cartb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.ecommerce.v1.cart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/darkclown97/api/services/ecommerce/v1/cart'
  _globals['_ADDTOCARTREQUEST']._serialized_start=125
  _globals['_ADDTOCARTREQUEST']._serialized_end=181
  _globals['_ADDTOCARTRESPONSE']._serialized_start=183
  _globals['_ADDTOCARTRESPONSE']._serialized_end=231
  _globals['_REMOVEFROMCARTREQUEST']._serialized_start=233
  _globals['_REMOVEFROMCARTREQUEST']._serialized_end=294
  _globals['_REMOVEFROMCARTRESPONSE']._serialized_start=296
  _globals['_REMOVEFROMCARTRESPONSE']._serialized_end=349
  _globals['_CLEARCARTREQUEST']._serialized_start=351
  _globals['_CLEARCARTREQUEST']._serialized_end=369
  _globals['_CLEARCARTRESPONSE']._serialized_start=371
  _globals['_CLEARCARTRESPONSE']._serialized_end=390
  _globals['_VIEWCARTREQUEST']._serialized_start=392
  _globals['_VIEWCARTREQUEST']._serialized_end=409
  _globals['_CARTITEM']._serialized_start=411
  _globals['_CARTITEM']._serialized_end=498
  _globals['_VIEWCARTRESPONSE']._serialized_start=500
  _globals['_VIEWCARTRESPONSE']._serialized_end=603
  _globals['_CARTINTERNAL']._serialized_start=606
  _globals['_CARTINTERNAL']._serialized_end=752
  _globals['_CARTSERVICE']._serialized_start=755
  _globals['_CARTSERVICE']._serialized_end=1204
# @@protoc_insertion_point(module_scope)
