# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from services.ecommerce.v1 import cart_pb2 as services_dot_ecommerce_dot_v1_dot_cart__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in services/ecommerce/v1/cart_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CartServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddToCart = channel.unary_unary(
                '/services.ecommerce.v1.cart.CartService/AddToCart',
                request_serializer=services_dot_ecommerce_dot_v1_dot_cart__pb2.AddToCartRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_cart__pb2.AddToCartResponse.FromString,
                _registered_method=True)
        self.RemoveFromCart = channel.unary_unary(
                '/services.ecommerce.v1.cart.CartService/RemoveFromCart',
                request_serializer=services_dot_ecommerce_dot_v1_dot_cart__pb2.RemoveFromCartRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_cart__pb2.RemoveFromCartResponse.FromString,
                _registered_method=True)
        self.ClearCart = channel.unary_unary(
                '/services.ecommerce.v1.cart.CartService/ClearCart',
                request_serializer=services_dot_ecommerce_dot_v1_dot_cart__pb2.ClearCartRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_cart__pb2.ClearCartResponse.FromString,
                _registered_method=True)
        self.ViewCart = channel.unary_unary(
                '/services.ecommerce.v1.cart.CartService/ViewCart',
                request_serializer=services_dot_ecommerce_dot_v1_dot_cart__pb2.ViewCartRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_cart__pb2.ViewCartResponse.FromString,
                _registered_method=True)


class CartServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddToCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFromCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CartServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToCart,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_cart__pb2.AddToCartRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_cart__pb2.AddToCartResponse.SerializeToString,
            ),
            'RemoveFromCart': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFromCart,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_cart__pb2.RemoveFromCartRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_cart__pb2.RemoveFromCartResponse.SerializeToString,
            ),
            'ClearCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCart,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_cart__pb2.ClearCartRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_cart__pb2.ClearCartResponse.SerializeToString,
            ),
            'ViewCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewCart,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_cart__pb2.ViewCartRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_cart__pb2.ViewCartResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.ecommerce.v1.cart.CartService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('services.ecommerce.v1.cart.CartService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CartService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.cart.CartService/AddToCart',
            services_dot_ecommerce_dot_v1_dot_cart__pb2.AddToCartRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_cart__pb2.AddToCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFromCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.cart.CartService/RemoveFromCart',
            services_dot_ecommerce_dot_v1_dot_cart__pb2.RemoveFromCartRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_cart__pb2.RemoveFromCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.cart.CartService/ClearCart',
            services_dot_ecommerce_dot_v1_dot_cart__pb2.ClearCartRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_cart__pb2.ClearCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.cart.CartService/ViewCart',
            services_dot_ecommerce_dot_v1_dot_cart__pb2.ViewCartRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_cart__pb2.ViewCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
