# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from services.ecommerce.v1.gateway import buyer_pb2 as services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in services/ecommerce/v1/gateway/buyer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BuyerGatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListProducts = channel.unary_unary(
                '/services.ecommerce.v1.gateway.BuyerGateway/ListProducts',
                request_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ListProductsRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ListProductsResponse.FromString,
                _registered_method=True)
        self.GetProduct = channel.unary_unary(
                '/services.ecommerce.v1.gateway.BuyerGateway/GetProduct',
                request_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.GetProductRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.GetProductResponse.FromString,
                _registered_method=True)
        self.AddToCart = channel.unary_unary(
                '/services.ecommerce.v1.gateway.BuyerGateway/AddToCart',
                request_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.AddToCartRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.AddToCartResponse.FromString,
                _registered_method=True)
        self.RemoveFromCart = channel.unary_unary(
                '/services.ecommerce.v1.gateway.BuyerGateway/RemoveFromCart',
                request_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.RemoveFromCartRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.RemoveFromCartResponse.FromString,
                _registered_method=True)
        self.ClearCart = channel.unary_unary(
                '/services.ecommerce.v1.gateway.BuyerGateway/ClearCart',
                request_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ClearCartRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ClearCartResponse.FromString,
                _registered_method=True)
        self.ViewCart = channel.unary_unary(
                '/services.ecommerce.v1.gateway.BuyerGateway/ViewCart',
                request_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ViewCartRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ViewCartResponse.FromString,
                _registered_method=True)
        self.CreateOrder = channel.unary_unary(
                '/services.ecommerce.v1.gateway.BuyerGateway/CreateOrder',
                request_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.CreateOrderRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.CreateOrderResponse.FromString,
                _registered_method=True)
        self.ListOrders = channel.unary_unary(
                '/services.ecommerce.v1.gateway.BuyerGateway/ListOrders',
                request_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ListOrdersRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ListOrdersResponse.FromString,
                _registered_method=True)
        self.GetOrders = channel.unary_unary(
                '/services.ecommerce.v1.gateway.BuyerGateway/GetOrders',
                request_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.GetOrdersRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.GetOrdersResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/services.ecommerce.v1.gateway.BuyerGateway/CancelOrder',
                request_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.CancelOrderResponse.FromString,
                _registered_method=True)


class BuyerGatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListProducts(self, request, context):
        """Product-related APIs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToCart(self, request, context):
        """Cart-related APIs  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFromCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrder(self, request, context):
        """Order-related APIs  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuyerGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProducts,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ListProductsRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ListProductsResponse.SerializeToString,
            ),
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.GetProductRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.GetProductResponse.SerializeToString,
            ),
            'AddToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToCart,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.AddToCartRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.AddToCartResponse.SerializeToString,
            ),
            'RemoveFromCart': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFromCart,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.RemoveFromCartRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.RemoveFromCartResponse.SerializeToString,
            ),
            'ClearCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCart,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ClearCartRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ClearCartResponse.SerializeToString,
            ),
            'ViewCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewCart,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ViewCartRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ViewCartResponse.SerializeToString,
            ),
            'CreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrder,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.CreateOrderRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.CreateOrderResponse.SerializeToString,
            ),
            'ListOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOrders,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ListOrdersRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ListOrdersResponse.SerializeToString,
            ),
            'GetOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrders,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.GetOrdersRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.GetOrdersResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.CancelOrderRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.CancelOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.ecommerce.v1.gateway.BuyerGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('services.ecommerce.v1.gateway.BuyerGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BuyerGateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.gateway.BuyerGateway/ListProducts',
            services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ListProductsRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ListProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.gateway.BuyerGateway/GetProduct',
            services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.GetProductRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.GetProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.gateway.BuyerGateway/AddToCart',
            services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.AddToCartRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.AddToCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFromCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.gateway.BuyerGateway/RemoveFromCart',
            services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.RemoveFromCartRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.RemoveFromCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.gateway.BuyerGateway/ClearCart',
            services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ClearCartRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ClearCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.gateway.BuyerGateway/ViewCart',
            services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ViewCartRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ViewCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.gateway.BuyerGateway/CreateOrder',
            services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.CreateOrderRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.CreateOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.gateway.BuyerGateway/ListOrders',
            services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ListOrdersRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.ListOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.gateway.BuyerGateway/GetOrders',
            services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.GetOrdersRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.GetOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.gateway.BuyerGateway/CancelOrder',
            services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.CancelOrderRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_gateway_dot_buyer__pb2.CancelOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
