# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from services.ecommerce.v1.gateway import seller_pb2 as services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in services/ecommerce/v1/gateway/seller_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SellerGatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListProducts = channel.unary_unary(
                '/services.ecommerce.v1.gateway.SellerGateway/ListProducts',
                request_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.ListProductsRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.ListProductsResponse.FromString,
                _registered_method=True)
        self.GetProduct = channel.unary_unary(
                '/services.ecommerce.v1.gateway.SellerGateway/GetProduct',
                request_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.GetProductRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.GetProductResponse.FromString,
                _registered_method=True)
        self.CreateProduct = channel.unary_unary(
                '/services.ecommerce.v1.gateway.SellerGateway/CreateProduct',
                request_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.CreateProductRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.CreateProductResponse.FromString,
                _registered_method=True)
        self.UpdateProduct = channel.unary_unary(
                '/services.ecommerce.v1.gateway.SellerGateway/UpdateProduct',
                request_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.UpdateProductRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.UpdateProductResponse.FromString,
                _registered_method=True)
        self.DeleteProduct = channel.unary_unary(
                '/services.ecommerce.v1.gateway.SellerGateway/DeleteProduct',
                request_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.DeleteProductRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.DeleteProductResponse.FromString,
                _registered_method=True)
        self.ListOrders = channel.unary_unary(
                '/services.ecommerce.v1.gateway.SellerGateway/ListOrders',
                request_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.ListOrdersRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.ListOrdersResponse.FromString,
                _registered_method=True)
        self.GetOrders = channel.unary_unary(
                '/services.ecommerce.v1.gateway.SellerGateway/GetOrders',
                request_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.GetOrdersRequest.SerializeToString,
                response_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.GetOrdersResponse.FromString,
                _registered_method=True)


class SellerGatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListProducts(self, request, context):
        """Product-related APIs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOrders(self, request, context):
        """Order-related APIs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SellerGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProducts,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.ListProductsRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.ListProductsResponse.SerializeToString,
            ),
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.GetProductRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.GetProductResponse.SerializeToString,
            ),
            'CreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProduct,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.CreateProductRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.CreateProductResponse.SerializeToString,
            ),
            'UpdateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProduct,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.UpdateProductRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.UpdateProductResponse.SerializeToString,
            ),
            'DeleteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProduct,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.DeleteProductRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.DeleteProductResponse.SerializeToString,
            ),
            'ListOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOrders,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.ListOrdersRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.ListOrdersResponse.SerializeToString,
            ),
            'GetOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrders,
                    request_deserializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.GetOrdersRequest.FromString,
                    response_serializer=services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.GetOrdersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.ecommerce.v1.gateway.SellerGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('services.ecommerce.v1.gateway.SellerGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SellerGateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.gateway.SellerGateway/ListProducts',
            services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.ListProductsRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.ListProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.gateway.SellerGateway/GetProduct',
            services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.GetProductRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.GetProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.gateway.SellerGateway/CreateProduct',
            services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.CreateProductRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.CreateProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.gateway.SellerGateway/UpdateProduct',
            services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.UpdateProductRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.UpdateProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.gateway.SellerGateway/DeleteProduct',
            services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.DeleteProductRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.DeleteProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.gateway.SellerGateway/ListOrders',
            services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.ListOrdersRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.ListOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ecommerce.v1.gateway.SellerGateway/GetOrders',
            services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.GetOrdersRequest.SerializeToString,
            services_dot_ecommerce_dot_v1_dot_gateway_dot_seller__pb2.GetOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
